import "@/styles/globals.scss";
import Layout from "@/components/layout/Layout";
import Head from "next/head";
import { GlobalProvider } from "@/hooks/useGlobalContext";
import { DevSupport } from "@react-buddy/ide-toolbox";
import { ComponentPreviews, useInitial } from "@/components/dev";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalProvider>
        <Layout>
          <DevSupport
            ComponentPreviews={ComponentPreviews}
            useInitialHook={useInitial}
          >
            <Component {...pageProps} />
          </DevSupport>
        </Layout>
      </GlobalProvider>
    </>
  );
}
